### ISSUE TITLE
package manage 파일이 두 개네요

### ISSUE THREAD

**Issue by kangkong0805** [Gmu-Wiki/Gmu-WiKi-Front-V2#106]
![image](https://github.com/Gmu-Wiki/Gmu-WiKi-Front-V2/assets/87346613/06b4ce68-2e4b-4bb6-9b17-43960413461c)
둘 중 하나만 사용하는 것이 좋습니다

**Comment by apnalkkamkkamhanjoon** [comment]
넵!!

**Comment by apnalkkamkkamhanjoon** [comment]
![image](https://github.com/Gmu-Wiki/Gmu-WiKi-Front-V2/assets/106512781/1c39cc21-57f7-49d8-87e2-dd8793c4284b)
반영 했습니다
