### ISSUE TITLE
문의 작성할 때 ux 개선

### ISSUE THREAD

**Issue by kangkong0805** [Gmu-Wiki/Gmu-WiKi-Front-V2#110]
| Gmu Wiki | Notion |
| - | - |
| ![image](https://github.com/Gmu-Wiki/Gmu-WiKi-Front-V2/assets/87346613/66aea583-3b33-44ba-91c3-829aec9bdcf8) | ![image](https://github.com/Gmu-Wiki/Gmu-WiKi-Front-V2/assets/87346613/51a377c4-956a-49a2-9d67-8864a0ca248e) |

문의 작성할 때 markdown을 잘 모르는 사용자들은 옵션 기능을 잘 활용하기 어려울 것 같아요
옵션을 hover 했을 때 tooltip을 띄우는 방법 등을 통해 ux를 개선하는 것도 좋을 것 같아요

**Comment by likegitman** [comment]
디자인 완성되면 바로 적용하겠습니다!
